# Generated by Django 4.0.4 on 2022-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_order_remove_order_client_delete_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('icon', models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-linkedin', 'Linkedin'), ('fa-instagram', 'Instagram'), ('fa-whatsapp', 'Whatsapp'), ('fa-phone', 'Phone'), ('fa-calculator', 'Calculator')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
